# I'm old!
name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build_script: ./buildallprojects
            build_cmd: ""
            artifact_name: hl1mp-linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Python
        run: sudo apt-get install -y python3

      - name: Install build dependencies
        run: |
          sudo apt-get install -y g++-multilib ninja-build lib32z1-dev podman

      - name: Create ccache folder
        run: mkdir -p /home/runner/.ccache
        shell: bash

      - name: Build
        run: ${{ matrix.build_script }}
        working-directory: src
        shell: bash

      - name: Upload Game Folder
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: game/
